services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "0:0"  # Run as root to avoid permission issues
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0:0"  # Run as root to avoid permission issues
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana_data:/var/lib/grafana